### ISSUE TITLE
Wrong widget name

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/shapely-companion#14]
![22d8318e4b620ce1ec9cadc3b77f9bc9](https://user-images.githubusercontent.com/26008574/27070200-a0ba79d6-5020-11e7-8297-1b9e3b744b3a.png)

**Comment by mplusb** [comment]
Also Vimeo videos do not change their height based on the widget settings

**Comment by cristianraiber** [comment]
@mplusb - good catch.
