### ISSUE TITLE
Strings not translatable in class-shapely-home-contact.php

### ISSUE THREAD

**Issue by claudiofus** [ColorlibHQ/shapely-companion#28]
Hi, I probably found a bug in your plugin. In class-shapely-home-contact.php at line 94, 99, 104 
`echo '<p class="mb0"><strong>' . __( 'Phone :', 'shapely-companion' ) . '</strong></p>';`
`echo '<p class="mb0"><strong>' . __( 'Email :', 'shapely-companion' ) . '</strong></p>';`
`echo '<p class="mb0"><strong>' . __( 'Address :', 'shapely-companion' ) . '</strong></p>';`
there are some hard-coded string that cannot be translated from any other plugin like Polylang, Loco etc and I don't think users must modify the plugin code. Could you please check that? 
Thanks for you work and this plugin!

**Comment by giucu91** [comment]
I think it's correct, can you check @cristian-e to make sure everything is ok ?

**Comment by bartus84** [comment]
Same issue here. Just installed WPML and these words cannot be translated.
