### ISSUE TITLE
strip_tags vs wp_kses in widgets

### ISSUE THREAD

**Issue by pad52** [ColorlibHQ/shapely-companion#3]
I think giving to users the possibility to style their text in widgets could be a good choice.
So I would prefer using wp_kses for widget content.

**Comment by cristianraiber** [comment]
@pad52 - I second this.

**Comment by cristianraiber** [comment]
@pad52 - feel free to download this version of the plugin: https://wordpress.org/plugins/shapely-companion/ (v 1.0.3). Changes / fixes have been pushed.
