### ISSUE TITLE
Shapely Companion ERROR upon activating

### ISSUE THREAD

**Issue by kupoback** [ColorlibHQ/shapely-companion#4]
After installing the Shapely Theme, I started installing the recommended plugins, one being Shapely Companion. [Reference support ticket](https://colorlib.com/wp/forums/topic/issue-installing-shapely-companion/#post-84844)

Upon activating the plugin, I receive this error:

    Parse error: syntax error, unexpected '[' in /nas/content/staging/domain/wp-content/plugins/shapely-companion/inc/widgets/widget-home-clients.php on line 84

Any idea what the issue could be? I am running Theme beta, per Support suggestion, and WordPress 4.7.1

**Comment by cristianraiber** [comment]
@kupoback - what PHP version are you running?

**Comment by kupoback** [comment]
@cristianraiber Server is WPEngine running 5.3.1 

I am hoping to upgrade it to 7.1, as that's the next version WPEngine supports. 

If that's the issue.

**Comment by cristianraiber** [comment]
@kupoback I believe that is the issue, yes. I've tested this on PHP 7.1 and it's working just fine. Just FYI , all WP themes should normally only support the PHP version required by WP as displayed here: https://wordpress.org/about/requirements/

**Comment by cristeacosmin** [comment]
This is fixed in the newest version. The problem was from initiating an array using the brackets, instead of array()

PS: Problem was here: github.com/puikinsh/shapely-companion/blob/master/inc/widgets/widget-home-clients.php#L83
