### ISSUE TITLE
Shapely Companion crashes WP

### ISSUE THREAD

**Issue by earto** [ColorlibHQ/shapely-companion#6]
Hi. I followed the guide to install Shapely and the required plugins.
When importing widgets I receive ‘Site does not support widget’ error for all widgets.
As per the forum post below, I installed "Shapely Companion".
https://colorlib.com/wp/forums/topic/shapely-theme-activated-but-cannot-import-widgets/

When I click "Activate" my WP site crashes completely.
Only way to fix the problem is delete Shapely Companion widget using FTP.
I also tried wiping my whole WP site/database and started with fresh WP - same problem.
I tried beta versions of Shapely and Shapely Companion.
Known issue?

Thanks.

**Comment by giucu91** [comment]
@cristianraiber @c0sm1n87 I think the problem is that the companion isn't installed and activated. As for the second problem, I believe the problem is the PHP version, same problem as here : #4.
How I should proceed with this?

**Comment by cristeacosmin** [comment]
Please provide more information on this matter. Use wp_debug and let us know where and when it crashes. At the current moment, shapely-companion passes the travis builds without any problems.

**Comment by cristianraiber** [comment]
Marking this as closed as there wasn't sufficient information provided by the reporter.
