### ISSUE TITLE
Shapely Companion error when activating:../widget-home-clients.php on line 84

### ISSUE THREAD

**Issue by laranz** [ColorlibHQ/shapely-companion#8]
We use this,

		`if ( ! isset( $logos['img'] ) ) {
			$logos['img'] = [ '' ];
		}
		if ( ! isset( $logos['link'] ) ) {
			$logos['link'] = [ '' ];
		}`

This type of array initialization is support only after PHP 5.4+ so for backward compatibility we should use 

`$logos['img'] = array();`

Just for the old users.

https://colorlib.com/wp/forums/topic/shapely-companion-error-when-activating-widget-home-clients-php-on-line-84/#post-89851

**Comment by cristianraiber** [comment]
@laranz - see this: https://wordpress.org/about/requirements/ 

WP recommends PHP  7.x+ as a minimum recommended. Supporting older PHP versions is not something that I personally am too fond of. I feel it creates a lot of problems and that it's actually the user's responsibility to make sure they're running the latest (and most stable) PHP version. 

cc @puikinsh - any thoughts on this?

**Comment by puikinsh** [comment]
Most hosting providers these days support at least PHP 5.6, so I see no point supporting anything below PHP 5.4. Sites that runs on older version of PHP can be easily updated via cPanel or by requesting that to the hosting provider.

**Comment by cristianraiber** [comment]
Marking this as invalid and closing.
